modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="deep_sea_exploration"
version="1.0.0"
displayName="Deep Sea exploration"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="lmman, MCreator"

[[dependencies.deep_sea_exploration]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




